#%RAML 0.8
title: Create shopping cart order
version: v0.1
baseUri: http://localhost:8081/api/{version}
/createShoppingCart:
  post:
    description: Create a shopping cart.
    body:
      application/json:
        schema: !include create-shopping-cart-json.schema
        example: !include create-shopping-cart-json.example
    responses:
      200:
        body:
          application/json:
            example: |
              {
                "name":"kalyan",
                "dept":"IT"
              }